name: Deploy_CD

on:
  repository_dispatch:
    types: [deploy_frontend]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Stop old containers
        run: docker compose down

      - name: Pull images
        run: docker compose pull

      - name: Start containers
        run: docker compose up -d
